version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: demo-mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo

  gachagameapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoadmin:password@mongo:27017/gachagame
